image: docker:latest

services:
  - docker:dind
  - mysql:latest

variables:
  STAGING_REGISTRY: "registry.gitlab.com"
  CONTAINER_TEST_IMAGE: ${STAGING_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_test
  CONTAINER_RELEASE_IMAGE: ${STAGING_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  MYSQL_DATABASE: trustpilot_widgets
  MYSQL_ROOT_PASSWORD: magento2
  MYSQL_USER: magento2
  MYSQL_PASSWORD: magento2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $STAGING_REGISTRY

stages:
  - build

build:
  stage: build
  script:
    - docker build --build-arg m2_publickey=$MAGENTO_USERNAME --build-arg m2_privatekey=$MAGENTO_PASSWORD --build-arg m2_dbuser=$MYSQL_USER --build-arg m2_dbpass=$MYSQL_PASSWORD --build-arg m2_dbname=$MYSQL_DATABASE --pull -t $CONTAINER_TEST_IMAGE .
