image: epcallan/php7-testing-phpunit:7.1-phpunit5

before_script:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --prefer-dist

in_docker:
  stage: test
  script:
    - phpunit
  only:
    - develop
