<?php
// Get the store locale
$helper = $this->helper('Pillbox\TrustpilotWidgets\Helper\Data');
?>
<?php if($helper->isEnabled()) { ?>
<!-- TrustBox widget - Product Reviews MultiSource SEO (Beta) -->
<div class="trustpilot-widget"
	data-locale="<?php echo $helper->getStoreLocale();?>"
	data-template-id="5763bccae0a06d08e809ecbb"
	data-businessunit-id="<?php echo $helper->getBusinessUnitID(); ?>"
	data-style-height="<?php echo $block->getData('height');?>"
	data-style-width="<?php echo $block->getData('width');?>"
	data-theme="<?php echo $block->getData('theme');?>"
	data-sku="<?php echo $block->getData('sku');?>"
	data-name="<?php echo $block->getData('name');?>">
<a href="https://www.trustpilot.com/review/totallywicked-eliquid.com" target="_blank">Trustpilot</a>
</div>
<!-- End TrustBox widget -->
<?php } ?>
