<?php
// Get the store locale
$helper = $this->helper('Pillbox\TrustpilotWidgets\Helper\Data');
?>
<?php if($helper->isEnabled()) { ?>
<!-- TrustBox widget - Product Reviews SEO (Beta) -->
<div class="trustpilot-widget"
	data-locale="<?php echo $helper->getStoreLocale();?>"
	data-template-id="5717796816f630043868e2e8"
	data-businessunit-id="<?php echo $helper->getBusinessUnitID(); ?>"
	data-style-height="<?php echo $block->getData('height');?>"
	data-style-width="<?php echo $block->getData('width');?>"
	data-theme="<?php echo $block->getData('theme');?>"
	data-sku="<?php echo $block->getData('sku');?>"
	data-name="<?php echo $block->getData('name');?>">
<a href="/trustpilot-reviews" target="_blank">Trustpilot</a>
</div>
<!-- End TrustBox widget -->
<?php } ?>
