<?php
// Get the store locale
$helper = $this->helper('Pillbox\TrustpilotWidgets\Helper\Data');
?>
<?php if($helper->isEnabled()) { ?>
<!-- TrustBox widget - Product Mini MultiSource -->
<div class="trustpilot-widget"
	data-locale="<?php echo $helper->getStoreLocale();?>"
	data-template-id="577258fb31f02306e4e3aaf9"
	data-businessunit-id="<?php echo $helper->getBusinessUnitID(); ?>"
	data-style-height="<?php echo $block->getData('height');?>"
	data-style-width="<?php echo $block->getData('width');?>"
	data-theme="<?php echo $block->getData('theme');?>"
	data-sku="<?php echo $block->getData('sku');?>">
<a href="/trustpilot-reviews" target="_blank">Trustpilot</a>
</div>
<!-- End TrustBox widget -->
<?php } ?>
